// ─── Shared style object ───────────────────────────────────────────
export const ACCENT = "#1565C0"; // blue theme for dry-clean
export const ACCENT_LIGHT = "#E3F0FF";

export const S = {
  app: {
    fontFamily: "'Georgia', serif",
    background: "#F5F8FF",
    minHeight: "100vh",
    color: "#1A1A1A",
    maxWidth: 480,
    margin: "0 auto",
  },
  nav: {
    position: "sticky",
    top: 0,
    zIndex: 100,
    background: "#0D1F3C",
    borderBottom: `2px solid ${ACCENT}`,
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
  },
  navBrand: {
    color: "#90CAF9",
    fontSize: 15,
    fontWeight: "bold",
    letterSpacing: 0.5,
    padding: "13px 0",
    marginRight: "auto",
    lineHeight: 1.2,
    display: "flex",
    alignItems: "center",
    gap: 7,
  },
  navBrandSub: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 10,
    fontFamily: "sans-serif",
    letterSpacing: 1,
    fontWeight: "normal",
    display: "block",
    marginTop: 1,
  },
  navTab: (a) => ({
    color: a ? "#90CAF9" : "rgba(255,255,255,0.4)",
    fontSize: 12,
    fontFamily: "sans-serif",
    padding: "14px 12px",
    cursor: "pointer",
    border: "none",
    background: "none",
    borderBottom: a ? `2px solid #90CAF9` : "2px solid transparent",
    marginBottom: -2,
    letterSpacing: 0.5,
    whiteSpace: "nowrap",
  }),
  offlineBar: {
    background: ACCENT_LIGHT,
    borderBottom: `1px solid rgba(21,101,192,0.3)`,
    padding: "6px 16px",
    fontFamily: "sans-serif",
    fontSize: 11,
    color: ACCENT,
    display: "flex",
    alignItems: "center",
    gap: 6,
    justifyContent: "center",
  },
  page: { padding: 16 },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2,minmax(0,1fr))",
    gap: 10,
    marginBottom: 16,
  },
  metric: (v) => {
    const bg =
      {
        blue: ACCENT_LIGHT,
        green: "#EAF5EE",
        danger: "#FDECEA",
        default: "#FFFFFF",
      }[v] || "#FFFFFF";
    const bdr =
      {
        blue: "rgba(21,101,192,0.2)",
        green: "rgba(45,125,70,0.2)",
        danger: "rgba(192,57,43,0.2)",
        default: "rgba(0,0,0,0.08)",
      }[v] || "rgba(0,0,0,0.08)";
    return {
      background: bg,
      border: `0.5px solid ${bdr}`,
      borderRadius: 10,
      padding: "12px 14px",
    };
  },
  metricLabel: {
    fontSize: 10,
    fontFamily: "sans-serif",
    color: "#6B6B6B",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  metricValue: (v) => ({
    fontSize: 19,
    fontWeight: "bold",
    color:
      { blue: ACCENT, green: "#2D7D46", danger: "#C0392B", default: "#1A1A1A" }[
        v
      ] || "#1A1A1A",
    letterSpacing: -0.5,
  }),
  metricSub: {
    fontSize: 10,
    fontFamily: "sans-serif",
    color: "#6B6B6B",
    marginTop: 2,
  },
  secHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  secTitle: { fontSize: 17, color: "#1A1A1A", letterSpacing: -0.3 },
  btnPrimary: {
    background: "#0D1F3C",
    color: "#90CAF9",
    border: "none",
    padding: "8px 14px",
    borderRadius: 10,
    fontSize: 12,
    fontFamily: "sans-serif",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 5,
    letterSpacing: 0.3,
  },
  btnSm: { padding: "6px 10px", fontSize: 11, borderRadius: 8 },
  btnDanger: {
    background: "#FDECEA",
    color: "#C0392B",
    border: "1px solid rgba(192,57,43,0.2)",
  },
  btnCancel: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    fontFamily: "sans-serif",
    fontSize: 13,
    cursor: "pointer",
    border: "1px solid rgba(0,0,0,0.12)",
    background: "#F5F8FF",
    color: "#6B6B6B",
    fontWeight: 500,
  },
  btnSave: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    fontFamily: "sans-serif",
    fontSize: 13,
    cursor: "pointer",
    border: "none",
    background: "#0D1F3C",
    color: "#90CAF9",
    fontWeight: 500,
  },
  card: {
    background: "#FFFFFF",
    border: "0.5px solid rgba(0,0,0,0.08)",
    borderRadius: 14,
    padding: "14px 16px",
    marginBottom: 10,
  },
  cardName: { fontSize: 15, fontWeight: "bold", color: "#1A1A1A" },
  cardSub: {
    fontSize: 12,
    fontFamily: "sans-serif",
    color: "#6B6B6B",
    marginTop: 1,
  },
  cardMeta: {
    display: "grid",
    gridTemplateColumns: "repeat(2,minmax(0,1fr))",
    gap: 6,
    marginTop: 10,
  },
  metaItem: { fontFamily: "sans-serif", fontSize: 11 },
  metaLabel: { color: "#6B6B6B", marginBottom: 1 },
  metaVal: { color: "#1A1A1A", fontWeight: 500 },
  cardActions: {
    display: "flex",
    gap: 6,
    marginTop: 12,
    paddingTop: 10,
    borderTop: "0.5px solid rgba(0,0,0,0.08)",
  },
  badge: (variant) => {
    const map = {
      Pending: { bg: "#FFF3CD", color: "#856404" },
      "In Progress": { bg: "#E3F0FF", color: "#1565C0" },
      Ready: { bg: "#E8F5E9", color: "#2E7D32" },
      Collected: { bg: "#EAF5EE", color: "#2D7D46" },
      paid: { bg: "#EAF5EE", color: "#2D7D46" },
      partial: { bg: "#FFF3CD", color: "#856404" },
      unpaid: { bg: "#FDECEA", color: "#C0392B" },
      pickup: { bg: "#F3E5F5", color: "#7B1FA2" },
      delivery: { bg: "#E3F0FF", color: "#1565C0" },
    };
    const v = map[variant] || { bg: "#F1F3F5", color: "#555" };
    return {
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      fontFamily: "sans-serif",
      fontSize: 10,
      padding: "3px 8px",
      borderRadius: 20,
      fontWeight: 600,
      letterSpacing: 0.3,
      textTransform: "uppercase",
      whiteSpace: "nowrap",
      background: v.bg,
      color: v.color,
    };
  },
  searchWrap: { position: "relative", marginBottom: 12 },
  searchInput: {
    width: "100%",
    paddingLeft: 34,
    paddingRight: 12,
    paddingTop: 10,
    paddingBottom: 10,
    border: "1px solid rgba(0,0,0,0.15)",
    borderRadius: 10,
    fontSize: 13,
    fontFamily: "sans-serif",
    color: "#1A1A1A",
    background: "#fff",
    outline: "none",
    boxSizing: "border-box",
  },
  searchIconWrap: {
    position: "absolute",
    left: 10,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#9B9B9B",
    display: "flex",
  },
  filterRow: {
    display: "flex",
    gap: 6,
    marginBottom: 14,
    overflowX: "auto",
    paddingBottom: 4,
  },
  chip: (a) => ({
    fontFamily: "sans-serif",
    fontSize: 11,
    padding: "5px 12px",
    borderRadius: 20,
    border: a ? `1px solid ${ACCENT}` : "1px solid rgba(0,0,0,0.12)",
    background: a ? ACCENT_LIGHT : "#fff",
    cursor: "pointer",
    whiteSpace: "nowrap",
    color: a ? ACCENT : "#6B6B6B",
    letterSpacing: 0.3,
    fontWeight: a ? 600 : 400,
  }),
  divider: {
    fontFamily: "sans-serif",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#6B6B6B",
    margin: "16px 0 8px",
    paddingBottom: 4,
    borderBottom: "0.5px solid rgba(0,0,0,0.08)",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    zIndex: 200,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  modal: {
    background: "#fff",
    borderRadius: "14px 14px 0 0",
    width: "100%",
    maxWidth: 480,
    maxHeight: "92vh",
    overflowY: "auto",
    padding: "20px 18px 30px",
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: "0.5px solid rgba(0,0,0,0.08)",
  },
  formGroup: { marginBottom: 14 },
  formRow: {
    display: "grid",
    gridTemplateColumns: "repeat(2,minmax(0,1fr))",
    gap: 10,
  },
  label: {
    fontFamily: "sans-serif",
    fontSize: 11,
    color: "#6B6B6B",
    display: "block",
    marginBottom: 5,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    border: "1px solid rgba(0,0,0,0.15)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "sans-serif",
    color: "#1A1A1A",
    background: "#fff",
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    border: "1px solid rgba(0,0,0,0.15)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "sans-serif",
    color: "#1A1A1A",
    background: "#fff",
    outline: "none",
    resize: "vertical",
    minHeight: 70,
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    border: "1px solid rgba(0,0,0,0.15)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "sans-serif",
    color: "#1A1A1A",
    background: "#fff",
    outline: "none",
    boxSizing: "border-box",
  },
  modalActions: { display: "flex", gap: 8, marginTop: 18 },
  txAmount: (t) => ({
    fontFamily: "sans-serif",
    fontSize: 14,
    fontWeight: 600,
    color: t === "income" ? "#2D7D46" : "#C0392B",
  }),
  chartWrap: {
    background: "#fff",
    border: "0.5px solid rgba(0,0,0,0.08)",
    borderRadius: 14,
    padding: "14px 16px",
    marginBottom: 14,
  },
  empty: {
    textAlign: "center",
    padding: "40px 20px",
    color: "#9B9B9B",
    fontFamily: "sans-serif",
    fontSize: 13,
  },
};
